### ISSUE TITLE
Add code coverage for OpenSearch Dashboards

### ISSUE THREAD

**Issue by avivbenchorin** [tianleh/tianleh-test-cases#12] opened 2021-09-11 00:30 UTC
Cypress has a guide for incorporating code coverage functionality to test runs (located [here](https://docs.cypress.io/guides/tooling/code-coverage#Introduction)), which would be desirable to incorporate into Monterey to provide code coverage of OpenSearch Dashboards and its plugins. Initial experimentation with using source code instrumented by [`nyc`](https://docs.cypress.io/guides/tooling/code-coverage#Using-NYC) in OpenSearch Dashboards and using [`babel-plugin-istanbul`](https://docs.cypress.io/guides/tooling/code-coverage#Using-code-transpilation-pipeline) to instrument code during transpilation have both been unsuccessful. More research on the methods of instrumenting OpenSearch Dashboard's source code will be needed. 

Once the instrumentation process is successful, it will be possible to use the Cypress [code coverage plugin](https://github.com/cypress-io/code-coverage) to generate the final code coverage report.

**Comment by tianleh** [comment] 2022-01-25 23:08
Resolve as duplicate of https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/88

**Closed as completed by tianleh** 2022-01-25 23:08 UTC
Labels: enhancement
